agents/urls.py
from django.urls import path
from .views import AgentsListView, AgentsDetailView, MessageAgentCreateView

app_name = 'agents'

urlpatterns = [
    path('', AgentsListView.as_view(), name='list'),
    path('mess/to', MessageAgentCreateView.as_view(), name='message'),
    path('<slug:slug>/', AgentsDetailView.as_view(), name='detail'),

]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('agents/', include('agents.urls')),
    path('houses/', include('houses.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

houses/urls.py
from django.urls import path
from .views import HousesListView, HouseDetailView, search_house

app_name = 'houses'

urlpatterns = [
    path('list/', HousesListView.as_view(), name='list'),
    path('detail/<int:pk>/', HouseDetailView.as_view(), name='detail'),
    path('search/', search_house, name='search'),
]

pages/urls.py
from django.urls import path
from .views import IndexView, AboutUsView

app_name = 'pages'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutUsView.as_view(), name='about'),
]

agents/models.py
from django.db import models
from datetime import datetime

from django.urls import reverse


class Agent(models.Model):
    """ model Agent """
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    photo = models.ImageField(upload_to='agents_photo/%Y/%m/%d/')
    description = models.TextField(blank=True)
    email = models.CharField(max_length=50)
    phone = models.CharField(max_length=20)
    hire_date = models.DateTimeField(default=datetime.now, blank=True)
    is_best = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class MessageAgent(models.Model):
    """ model Message Agent """
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=50)
    comment = models.TextField()
    is_read = models.BooleanField(default=False)
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE)

    def __str__(self):
        return f'Comment from {self.name}'

    def get_absolute_url(self):
        return reverse('agents:message')

houses/models.py
from django.db import models
from datetime import datetime
from agents.models import Agent


class House(models.Model):
    """
        House model for db
    """
    VERY_POOR = 1
    POOR = 2
    FAIR = 3
    BELOW_AVERAGE = 4
    AVERAGE = 5
    ABOVE_AVERAGE = 6
    GOOD = 7
    VERY_GOOD = 8
    EXCELLENT = 9
    VERY_EXCELLENT = 10

    RATES = (
        (VERY_POOR, 'Very Poor'), (POOR, 'Poor'), (FAIR, 'Fair'), (BELOW_AVERAGE, 'Below Average'),
        (AVERAGE, 'Average'), (ABOVE_AVERAGE, 'Above Average'), (GOOD, 'Good'), (VERY_GOOD, 'Very Good'),
        (EXCELLENT, 'Excellent'), (VERY_EXCELLENT, 'Very Excellent')
    )

    realtor = models.ForeignKey(Agent, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=255)
    city = models.CharField(max_length=100)
    lat = models.FloatField()
    lng = models.FloatField()
    description = models.TextField(blank=True)
    price = models.IntegerField()
    bedrooms = models.IntegerField()
    bathrooms = models.IntegerField()
    area = models.IntegerField()
    year_build = models.IntegerField()
    total_room = models.IntegerField()
    building_type = models.CharField(max_length=255)
    overall_quality = models.SmallIntegerField(default=AVERAGE, choices=RATES)
    overall_condition = models.SmallIntegerField(default=AVERAGE, choices=RATES)

    list_date = models.DateTimeField(default=datetime.now, blank=True)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)

    def __str__(self):
        return self.title

pages/models.py
from django.db import models


class Comment(models.Model):
    """
        Comment model for db
    """
    name = models.CharField(max_length=50)
    comment = models.TextField()
    image = models.ImageField(upload_to='users_comment')

    def __str__(self):
        return self.name

agents/forms.py
from django import forms

from .models import MessageAgent


class MessageForm(forms.ModelForm):
    """ Form for messages to agents """
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control form-control-lg form-control-a',
        'placeholder': 'Name *'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control form-control-lg form-control-a',
        'placeholder': 'Email *'}))
    comment = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Comment *',
        'cols': '45',
        'rows': '8'
    }))

    class Meta:
        model = MessageAgent
        fields = ('name', 'email', 'comment')

agents/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from utils.views import TitleMixin
from .models import Agent, MessageAgent
from houses.models import House
from .forms import MessageForm


class AgentsListView(TitleMixin, ListView):
    """
    View for list agents
    """
    template_name = 'agents/list.html'
    model = Agent
    context_object_name = 'agents_list'
    title = 'Our agents'


class AgentsDetailView(TitleMixin, DetailView):
    """
    View for agent detail
    """
    template_name = 'agents/detail.html'
    model = Agent
    slug_url_kwarg = 'slug'
    context_object_name = 'agent'
    title = 'Agent'

    def get_context_data(self, **kwargs):
        """
        Getting a list of homes for our agent
        """
        data = super().get_context_data(**kwargs)
        data['house_list'] = House.objects.filter(realtor=self.object)
        return data


class MessageAgentCreateView(CreateView):
    """
    View for agent detail
    """
    model = MessageAgent
    form_class = MessageForm
    template_name = 'agents/mess.html'
    success_url = reverse_lazy('pages:index')

    def form_valid(self, form):
        """
        Checking the form for validity, adding data about the agent and saving the form
        """
        self.object = form.save(commit=False)
        self.object.agent = Agent.objects.get(id=form.data.get('agent_id'))
        self.object.save()

        return super(MessageAgentCreateView, self).form_valid(form)

houses/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from utils.views import TitleMixin
from .models import House


class HousesListView(TitleMixin, ListView):
    """
    View for list houses
    """
    template_name = 'houses/list.html'
    model = House
    context_object_name = 'houses_list'
    title = 'Our Amazing Houses'


class HouseDetailView(TitleMixin, DetailView):
    """
    View for house details
    """
    template_name = 'houses/detail.html'
    model = House
    context_object_name = 'house'
    title = 'House'


def search_house(request):
    """ Search in the db from the form """
    search = None
    keyword = request.GET.get('keyword')
    city = request.GET.get('city')
    bedrooms = request.GET.get('bedrooms')
    bathrooms = request.GET.get('bathrooms')
    price = request.GET.get('price')

    if keyword:
        search = House.objects.filter(Q(title__icontains=keyword) | Q(description__icontains=keyword))

    if city != 'All city':
        search = search.filter(city=city)

    if bedrooms != 'Any':
        search = search.filter(bedrooms=bedrooms)

    if bathrooms != 'Any':
        search = search.filter(bathrooms=bathrooms)

    if price != 'Unlimite':
        search = search.filter(price__gte=int(price))

    return render(request, 'houses/list.html', {'houses_list': search})

pages/views.py
from django.views.generic import TemplateView
from utils.views import TitleMixin


class IndexView(TitleMixin, TemplateView):
    """ TemplateView for index page"""
    template_name = 'pages/index.html'
    title = 'Estate Agency'


class AboutUsView(TitleMixin, TemplateView):
    """ TemplateView for about page"""
    template_name = 'pages/about.html'
    title = 'About us'

utils/views.py
class TitleMixin:
    """adding an attribute title """
    title = None

    def get_context_data(self, **kwargs):
        context = super(TitleMixin, self).get_context_data()
        context['title'] = self.title
        return context

templates/agents/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ title }} : {{ agent.name }}
{% endblock %}

{% block content %}
    <main id="main">

    <!-- ======= Intro Single ======= -->
    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <div class="title-single-box">
              <h1 class="title-single">{{ agent.name }}</h1>
              <span class="color-text-a">Agent Immobiliari</span>
            </div>
          </div>
          <div class="col-md-12 col-lg-4">
            <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="{% url 'pages:index' %}">Home</a>
                </li>
                <li class="breadcrumb-item">
                  <a href="{% url 'agents:list' %}">Agents</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  {{ agent.name }}
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section><!-- End Intro Single -->

    <!-- ======= Agent Single ======= -->
    <section class="agent-single">
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <div class="row">
              <div class="col-md-6">
                <div class="agent-avatar-box">
                  <img src="{{ agent.photo.url }}" alt="" class="agent-avatar img-fluid">
                </div>
              </div>
              <div class="col-md-5 section-md-t3">
                <div class="agent-info-box">
                  <div class="agent-title">
                    <div class="title-box-d">
                      <h3 class="title-d">{{ agent.name }}
                      </h3>
                    </div>
                  </div>
                  <div class="agent-content mb-3">
                    <p class="content-d color-text-a">
                      {{ agent.description }}
                    </p>
                    <div class="info-agents color-a">
                      <p>
                        <strong>Phone: </strong>
                        <span class="color-text-a"> {{ agent.phone }} </span>
                      </p>
                      <p>
                        <strong>Email: </strong>
                        <span class="color-text-a"> {{ agent.email }}</span>
                      </p>
                    </div>
                  </div>
{#                    TODO#}
                  <div class="socials-footer">
                    <ul class="list-inline">
                      <li class="list-inline-item">
                        <a href="#" class="link-one">
                          <i class="bi bi-facebook" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href="#" class="link-one">
                          <i class="bi bi-twitter" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href="#" class="link-one">
                          <i class="bi bi-instagram" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href="#" class="link-one">
                          <i class="bi bi-linkedin" aria-hidden="true"></i>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-12 section-t8">
            <div class="title-box-d">
              <h3 class="title-d">My Properties</h3>
            </div>
          </div>
          <div class="row property-grid grid">
              {% for house in house_list %}
            <div class="col-md-4">
            <div class="card-box-a card-shadow">
              <div class="img-box-a">
                <img src="{{ house.photo_main.url }}" alt="" class="img-a img-fluid">
              </div>
              <div class="card-overlay">
                <div class="card-overlay-a-content">
                  <div class="card-header-a">
                    <h2 class="card-title-a">
                      <a href="#">{{ house.city }}
                        <br /> {{ house.year_build }}</a>
                    </h2>
                  </div>
                  <div class="card-body-a">
                    <div class="price-box d-flex">
                      <span class="price-a">{{ house.price }}</span>
                    </div>
                    <a href="{% url 'houses:detail' house.pk %}" class="link-a">Click here to view
                      <span class="bi bi-chevron-right"></span>
                    </a>
                  </div>
                  <div class="card-footer-a">
                    <ul class="card-info d-flex justify-content-around">
                      <li>
                        <h4 class="card-info-title">Area</h4>
                        <span>{{ house.area }}m
                          <sup>2</sup>
                        </span>
                      </li>
                      <li>
                        <h4 class="card-info-title">Beds</h4>
                        <span>{{ house.bedrooms }}</span>
                      </li>
                      <li>
                        <h4 class="card-info-title">Baths</h4>
                        <span>{{ house.bathrooms }}</span>
                      </li>
                      <li>
                        <h4 class="card-info-title">Total Room</h4>
                        <span>{{ house.total_room }}</span>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
              {% endfor %}
          </div>
        </div>
      </div>
    </section>
<!-- End Agent Single -->
  </main>

{% endblock %}

templates/agents/mess.html
<div class="col-md-12 col-lg-4">
    <div class="property-contact">
        <form class="form-a" action="{% url 'agents:message' %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-12 mb-1">
                    <div class="form-group">
                        {{ form.name }}
                    </div>
                </div>
                <div class="col-md-12 mb-1">
                    <div class="form-group">
                        {{ form.email }}
                    </div>
                </div>
                <div class="col-md-12 mb-1">
                    <div class="form-group">
                        {{ form.comment }}
                    </div>
                </div>
                <input type="hidden" class="" name="agent_id" value="{{ id }}">
                <div class="col-md-12 mt-3">
                    <button type="submit" class="btn btn-a">Send Message</button>
                </div>
            </div>
        </form>
    </div>
</div>

templates/houses/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ title }} : {{ house.city }} ==> {{ house.price }} $
{% endblock %}

{% block content %}

    <main id="main">

    <!-- ======= Intro Single ======= -->
    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <div class="title-single-box">
              <h1 class="title-single">Beautiful house in {{ house.city }}</h1>
              <span class="color-text-a">{{ house.city }}, {{ house.lat }} : {{ house.lng }}</span>
            </div>
          </div>
          <div class="col-md-12 col-lg-4">
            <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="{% url 'pages:index' %}">Home</a>
                </li>
                <li class="breadcrumb-item">
                  <a href="{% url 'houses:list' %}">Houses</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  NOW
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section><!-- End Intro Single-->

    <!-- ======= Property Single ======= -->
    <section class="property-single nav-arrow-b">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8">
            <div id="property-single-carousel" class="swiper">
              <div class="swiper-wrapper">
                    {% if house.photo_1 %}
                        <div class="carousel-item-b swiper-slide">
                            <img src="{{ house.photo_1.url }}" alt="{{ house.title }}">
                        </div>
                    {% else %}
                        <div class="tab-pane fade show active">
                            <img src="{{ house.photo_main.url }}" alt="{{ house.title }}">
                        </div>
                    {% endif %}
                    {% if house.photo_2 %}
                        <div class="carousel-item-b swiper-slide">
                            <img src="{{ house.photo_2.url }}" alt="{{ house.title }}">
                        </div>
                    {% endif %}
                    {% if house.photo_3 %}
                        <div class="carousel-item-b swiper-slide">
                            <img src="{{ house.photo_3.url }}" alt="{{ house.title }}">
                        </div>
                    {% endif %}
              </div>
            </div>
            <div class="property-single-carousel-pagination carousel-pagination"></div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">

            <div class="row justify-content-between">
              <div class="col-md-5 col-lg-4">
                <div class="property-price d-flex justify-content-center foo">
                  <div class="card-header-c d-flex">
                    <div class="card-box-ico">
                      <span class="bi bi-cash">$</span>
                    </div>
                    <div class="card-title-c align-self-center">
                      <h5 class="title-c">{{ house.price }}</h5>
                    </div>
                  </div>
                </div>
                <div class="property-summary">
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="title-box-d section-t4">
                        <h3 class="title-d">Quick Summary</h3>
                      </div>
                    </div>
                  </div>
                  <div class="summary-list">
                    <ul class="list">
                      <li class="d-flex justify-content-between">
                        <strong>Year building:</strong>
                        <span>{{ house.year_build }}</span>
                      </li>
                      <li class="d-flex justify-content-between">
                        <strong>Location:</strong>
                        <span>{{ house.city }}, {{ house.lat }} : {{ house.lng }}</span>
                      </li>
                      <li class="d-flex justify-content-between">
                        <strong>Property Type:</strong>
                        <span>{{ house.building_type }}</span>
                      </li>
                      <li class="d-flex justify-content-between">
                        <strong>Area:</strong>
                        <span>{{ house.area }}m
                          <sup>2</sup>
                        </span>
                      </li>
                      <li class="d-flex justify-content-between">
                        <strong>Beds:</strong>
                        <span>{{ house.bedrooms }}</span>
                      </li>
                      <li class="d-flex justify-content-between">
                        <strong>Baths:</strong>
                        <span>{{ house.bathrooms }}</span>
                      </li>
                      <li class="d-flex justify-content-between">
                        <strong>Total room:</strong>
                        <span>{{ house.total_room }}</span>
                      </li>
                      <li class="d-flex justify-content-between">
                        <strong>Overall condition:</strong>
                        <span>{{ house.get_overall_condition_display }}</span>
                      </li>
                      <li class="d-flex justify-content-between">
                        <strong>Overall quality:</strong>
                        <span>{{ house.get_overall_quality_display }}</span>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-md-7 col-lg-7 section-md-t3">
                <div class="row">
                  <div class="col-sm-12">
                    <div class="title-box-d">
                      <h3 class="title-d">Property Description</h3>
                    </div>
                  </div>
                </div>
                <div class="property-description">
                  <p class="description color-text-a">
                      {{ house.description }}
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-12">
            <div class="row section-t3">
              <div class="col-sm-12">
                <div class="title-box-d">
                  <h3 class="title-d">Contact Agent</h3>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6 col-lg-4">
                <img src="{{ house.realtor.photo.url }}" alt="" class="img-fluid">
              </div>
              <div class="col-md-6 col-lg-4">
                <div class="property-agent">
                    <a href="{% url 'agents:detail' house.realtor.slug %}"><h4 class="title-agent">{{ house.realtor.name }}</h4></a>
                  <p class="color-text-a">
                    {{ house.realtor.description|truncatewords:50 }}
                  </p>
                  <ul class="list-unstyled">
                    <li class="d-flex justify-content-between">
                      <strong>Phone:</strong>
                      <span class="color-text-a">{{ house.realtor.phone }}</span>
                    </li>
                    <li class="d-flex justify-content-between">
                      <strong>Email:</strong>
                      <span class="color-text-a">{{ house.realtor.email }}</span>
                    </li>
                  </ul>
{#                    TODO#}
                  <div class="socials-a">
                    <ul class="list-inline">
                      <li class="list-inline-item">
                        <a href="#">
                          <i class="bi bi-facebook" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href="#">
                          <i class="bi bi-twitter" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href="#">
                          <i class="bi bi-instagram" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href="#">
                          <i class="bi bi-linkedin" aria-hidden="true"></i>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
                {% load agents_tags %}
                {% get_callback_form house.realtor.id %}
            </div>
          </div>
        </div>
      </div>
    </section><!-- End Property Single-->

  </main><!-- End #main -->
{% endblock %}

templates/inc/_footer.html
{% load static %}

  <section class="section-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-4">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">EstateAgency</h3>
            </div>
            <div class="w-body-a">
              <p class="w-text-a color-text-a">
                Enim minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip exea commodo consequat duis
                sed aute irure.
              </p>
            </div>
            <div class="w-footer-a">
              <ul class="list-unstyled">
                <li class="color-a">
                  <span class="color-text-a">Phone .</span> contact@example.com
                </li>
                <li class="color-a">
                  <span class="color-text-a">Email .</span> +54 356 945234
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-sm-12 col-md-4 section-md-t3">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">The Company</h3>
            </div>
            <div class="w-body-a">
              <div class="w-body-a">
                <ul class="list-unstyled">
                  <li class="item-list-a">
                    <i class="bi bi-chevron-right"></i> <a href="{% url 'admin:login' %}">Agent Admin</a>
                  </li>
                  <li class="item-list-a">
                    <i class="bi bi-chevron-right"></i> <a href="#">Privacy Policy</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-12 col-md-4 section-md-t3">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">International sites</h3>
            </div>
            <div class="w-body-a">
              <ul class="list-unstyled">
                <li class="item-list-a">
                  <i class="bi bi-chevron-right"></i> <a href="#">Venezuela</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <nav class="nav-footer">
            <ul class="list-inline">
              <li class="list-inline-item">
                <a href="{% url 'pages:index' %}">Home</a>
              </li>
              <li class="list-inline-item">
                <a href="{% url 'pages:about' %}">About</a>
              </li>
              <li class="list-inline-item">
                <a href="{% url 'agents:list' %}">Agents</a>
              </li>
              <li class="list-inline-item">
                <a href="{% url 'houses:list' %}">Houses</a>
              </li>
            </ul>
          </nav>
          <div class="socials-a">
            <ul class="list-inline">
              <li class="list-inline-item">
                <a href="#">
                  <i class="bi bi-facebook" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="bi bi-twitter" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="bi bi-instagram" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="bi bi-linkedin" aria-hidden="true"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="copyright-footer">
            <p class="copyright color-text-a">
              &copy; Copyright
              <span class="color-a">EstateAgency</span> All Rights Reserved. {% now 'Y' %} -
            </p>
          </div>

        </div>
      </div>
    </div>
  </footer>

templates/inc/_header.html
{% load static %}
<nav class="navbar navbar-default navbar-trans navbar-expand-lg fixed-top">
    <div class="container">
        <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDefault"
                aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span></span>
            <span></span>
            <span></span>
        </button>
        <a class="navbar-brand text-brand" href="{% url 'pages:index' %}">Estate<span class="color-b">Agency</span></a>

        <div class="navbar-collapse collapse justify-content-center" id="navbarDefault">
            <ul class="navbar-nav" id="myTab">

                <li class="nav-item">
                    <a class="nav-link " href="{% url 'pages:index' %}">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link " href="{% url 'pages:about' %}">About</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link " href="{% url 'agents:list' %}">Agents</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link " href="{% url 'houses:list' %}">Houses</a>
                </li>
            </ul>
        </div>

        <button type="button" class="btn btn-b-n navbar-toggle-box navbar-toggle-box-collapse" data-bs-toggle="collapse"
                data-bs-target="#navbarTogglerDemo01">
            <i class="bi bi-search"></i>
        </button>

    </div>
</nav>